# Define a ordem e o formato dos módulos com suporte a multi-linha e conectores
format = """
[┌─](fg:#313244)\
[░▒▓](fg:#313244)\
[  ](bg:#313244 fg:#cdd6f4)\
[](fg:#313244 bg:#45475a)\
$directory\
[](fg:#45475a bg:#585b70)\
$git_branch\
$git_status\
[](fg:#585b70)\
$cmd_duration
[└─](fg:#313244)\
$character"""

[directory]
style = "bg:#45475a fg:#cdd6f4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#585b70 fg:#cdd6f4"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#585b70 fg:#cdd6f4"
format = "[($all_status$ahead_behind)]($style)"

[character]
success_symbol = "[ ➜ ](bold fg:#cdd6f4)"
error_symbol = "[ ➜ ](bold fg:#f38ba8)"

[cmd_duration]
min_time = 500
style = "fg:#f9e2af"
format = " levou [$duration]($style) "
